processes:
  - name: "test_app.exe"
    args: []
    ports: [8080]
    health_checks: ["http://localhost:8080/health"]
    check_interval: 10
    restart_delay: 5
    kill_on_exit: false
    exclude_processes: ["notepad.exe"]  # 当记事本运行时不启动/重启测试应用