# 进程监控器配置文件示例
# 包含进程监控和注册表监控配置

# 进程监控配置
processes:
  - name: "notepad.exe"                # 要监控的进程名称
    enable: true                       # 是否启用此监控配置（可选，默认为true）
    args: []                           # 启动进程的参数
    restart_command: "notepad.exe"     # 重启时使用的命令（可选，默认使用name）
    work_dir: "C:\\Windows\\System32"                       # 工作目录（可选）
    ports: []                          # 要监控的端口（可选）
    health_checks: []                  # 健康检查URL（可选）
    check_interval: 10                 # 检查间隔（秒）
    restart_delay: 5                   # 重启延迟（秒）
    kill_on_exit: false                 # 监控器退出时是否杀死进程
    exclude_processes: []              # 排斥进程列表（如果这些进程存在，则不启动当前进程）

# 注册表监控配置（仅Windows系统有效）
registry_monitors:
  - name: "Windows自动登录监控"
    root_key: "HKLM"
    path: "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon"
    values:
      - name: "AutoAdminLogon"
        type: "string"
        expect_value: "1"                  # 1表示启用自动登录
      - name: "DefaultUserName"
        type: "string"
        expect_value: "Admin"
      - name: "DefaultPassword"
        type: "string"
        expect_value: "123456"
      - name: "DefaultDomainName"
        type: "string"
        # 不设置expect_value，只监控变化
      - name: "AutoLogonSID"
        type: "string"
    check_interval: 60                     # 每60秒检查一次
    execute_on_change: false                # 值变化时执行命令
    command: "powershell.exe"


# 注册表监控功能说明：
# values 配置项定义了要监控的注册表值：
# - name: 值名称
# - type: 值类型（支持 string, expand_string, binary, dword, multi_string, qword）
# - expect_value: 期望值（可选，用于验证值是否符合预期）
#
# execute_on_change: 控制是否在值变化时执行命令
# - true: 值变化时执行指定的命令
# - false: 只记录变化，不执行命令
#
# 环境变量传递：
# 当配置了命令执行时，以下环境变量会传递给命令：
# - CHANGED_VALUES: 发生变化的值名称列表（逗号分隔）
# - EXPECT_VALUE_MATCH: 是否所有变化的值都匹配期望值（true/false）